import Head from 'next/head'

import { Button } from 'antd'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        On the right is an antd primary button{' '}
        <Button type="primary">Hello World!</Button>
      </main>
    </div>
  )
}
