import Head from 'next/head'

import { Card, Button } from 'antd'

import s from 'styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Card className={s.mainCard}>
          On the right is an antd primary button{' '}
          <Button type="primary">Hello World!</Button>
        </Card>
      </main>
    </div>
  )
}
